name: Deploy Vercel

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  VERCEL_ORG_ID: team_5ADJjttgTBouoIYWUrrQlSfb
  VERCEL_PROJECT_ID: prj_WxQZwsLPTnSDKCSe8QkD49hVxRRI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Deploy to Vercel
        run: npx --yes vercel@latest --prod --yes --token="${{ secrets.VERCEL_TOKEN }}"
